export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const VERIFY_USER = "VERIFY_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const SET_ERROR = "SET_ERROR";

export const NEW_EXERCISE = "NEW_EXERCISE";
export const ADD_EXERCISE = "ADD_EXERCISE";
export const UPDATE_EXERCISE = "UPDATE_EXERCISE";
export const UPDATE_EXERCISE_STATE = "UPDATE_EXERCISE_STATE";
export const DELETE_EXERCISE = "DELETE_EXERCISE";
export const DELETE_EXERCISE_STATE = "DELETE_EXERCISE_STATE";

export const ADD_WORKOUT = "ADD_WORKOUT";
export const ADD_WORKOUT_STATE = "ADD_WORKOUT_STATE";






